config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import HomePageView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView, CreateCommentView, AddReactionView, PostsByTagView

app_name = 'posts'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("post/create/", PostCreateView.as_view(), name="post_create"),
    path("<int:pk>/", PostDetailView.as_view(), name="post_detail"),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),
    path("<int:pk>/comment/", CreateCommentView.as_view(), name="create_comment"),
    path('<int:pk>/react/<str:reaction_type>/', AddReactionView.as_view(), name='add_reaction'),
    path("tag/<str:tag_name>/", PostsByTagView.as_view(), name="posts_by_tag"),
]

comments/models.py
from django.db import models
from accounts.models import CustomUser
from posts.models import Post

class Comment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='comments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment {self.id} by {self.user.username} on {self.post.id}"

posts/models.py
from django.urls import reverse
from django.db import models
from accounts.models import CustomUser

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


STATUS_CHOICES = (
    ("Published", "Public"),
    ("Private", "Privé"),
    ("Draft", "Brouillon"),
)


class Post(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=700, db_index=True)
    content = models.TextField()
    post_image = models.ImageField(upload_to="images/", default="images/post1.jpg")
    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, related_name="posts", blank=True)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default="Draft")

    def __str__(self):
        return f"Post {self.id} by {self.user}"

    def get_absolute_url(self):
        return reverse("posts:post_detail", kwargs={"pk": self.pk})

    def total_reactions(self):
        return self.posts_reactions.count() or 0
    
    def total_comments(self):
        self.comment_set.all().count()

    def reaction_summary(self):
        return self.posts_reactions.values("reaction_type").annotate(
            count=models.Count("reaction_type")
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    content = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.id} | {self.user} | {self.content}"


class Reaction(models.Model):
    REACTION_TYPES = [
        ("like", "❤️"),
        ("laugh", "😄"),
        ("celebrate", "🎉"),
        ("insightful", "💡"),
        ("curious", "🤔"),
    ]

    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="users_reactions"
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="posts_reactions")
    reaction_type = models.CharField(max_length=20, choices=REACTION_TYPES)

    class Meta:
        unique_together = (
            "user",
            "post",
            "reaction_type",
        )

    def __str__(self):
        return f"{self.user} reacted {self.reaction_type} to {self.post}"

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content", "post_image", "tags", "status"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Entrez un titre"}
            ),
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Entrez ici le contenu",
                }
            ),
            "tags": forms.SelectMultiple(attrs={"class": "form-control"}),
            "status": forms.Select(attrs={"class": "form-control"}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

posts/views.py
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    View,
)
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect, render

from .models import Post, Comment, Reaction, Tag
from .forms import PostForm


class HomePageView(TemplateView):
    template_name = "posts/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.filter(status="Published")
        context["tags"] = Tag.objects.all()
        return context
    
class PostsByTagView(ListView):
    model = Post
    template_name = "posts/home.html" 
    context_object_name = "posts"

    def get_queryset(self):
        tag_name = self.kwargs.get("tag_name")
        return Post.objects.filter(tags__name=tag_name, status="Published")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["current_tag"] = self.kwargs.get("tag_name")
        return context


class PostListView(ListView):
    model = Post
    template_name = "posts/post_list.html"
    context_object_name = "posts"
    ordering = ["-created_at"]


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_form.html"
    success_url = reverse_lazy("posts:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostDetailView(DetailView):
    model = Post
    template_name = "posts/post_detail.html"
    context_object_name = "post"


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ["title", "content", "post_image", "tags", "status"]
    template_name = "posts/post_update.html"
    success_url = reverse_lazy("posts:home") 

    def form_valid(self, form):
        form.instance.user = (
            self.request.user
        )
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        return post.user == self.request.user


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "posts/post_confirm_delete.html"
    success_url = reverse_lazy("posts:home") 

    def test_func(self):
        post = self.get_object()
        return post.user == self.request.user


class CreateCommentView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        return render(request, "posts/create_comment.html", {"post": post})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        content = request.POST.get("content")
        if content:
            Comment.objects.create(post=post, user=request.user, content=content)
        return redirect("posts:post_detail", pk=pk)


class AddReactionView(View):
    def post(self, request, pk, reaction_type):
        post = get_object_or_404(Post, pk=pk)
        existing_reaction = Reaction.objects.filter(
            user=request.user, post=post, reaction_type=reaction_type
        )

        if existing_reaction.exists():
            existing_reaction.delete()
        else:
            Reaction.objects.update_or_create(
                user=request.user, post=post, reaction_type=reaction_type
            )

        return redirect("posts:post_detail", pk=pk)

posts/templates/posts/create_comment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <main class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="container p-0 mt-5">
          <div class="row mt-5">
            <div class="card col-md-6 offset-md-3 p-5 mt-5">
              <h1>Laisser un commentaire sur l'article: {{ post.title }}</h1>

              <form method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="content">Votre commentaire</label>
                  <textarea class="form-control" id="content" name="content" rows="4" required placeholder="Ecrivez ici..."></textarea>
                </div>

                <button type="submit" class="btn btn-primary mt-3">Submit</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <main class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="container p-0 mt-5">
          <div class="row mt-5">
            <div class="card col-md-6 offset-md-3 p-5 mt-5">
              <h2>Supression Article</h2>
              <p>Etes-vous sûr de vouloir supprimer cet article?</p>
              <p>
                <strong>{{ object.title }}</strong>
              </p>
              <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Oui, Supprimer</button>
                <a href="{% url 'posts:home' %}" class="btn btn-secondary">Annuler</a>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  {% include 'header.html' %}

  <main class="container position-relative">
    <div class="row">
      <asside class="asside-right col-md-1 d-none d-md-block">
        <div class="reactions">
          <div class="reactions__container">
            <div class="reactions__container--heart">
              <a href="#">
                <img src="{% static 'assets/icons/black-heart-Icon.svg' %}" />
                <p>{{ post.total_reactions }}</p>
              </a>
            </div>
            <div class="reactions__container--comment">
              <a href="#">
                <img src="{% static 'assets/icons/black-Flat-Icon.svg' %}" />
                <p>16</p>
              </a>
            </div>
            <div class="reactions__container--save">
              <a href="#">
                <img src="{% static 'assets/icons/book-Icon.svg' %}" />
                <p>100</p>
              </a>
            </div>
            <div class="reactions__container--dots">
              <a href="#"><img src="{% static 'assets/img/icons8-elipsis-28.webp' %}" /></a>
            </div>
          </div>
        </div>
      </asside>
      <section id="postView" class="col-12 col-md-10 col-lg-7">
        {% if user.is_authenticated and user == post.user %}
          <div class="d-flex justify-content-end mb-2">
            <a href="{% url 'posts:post_update' post.pk %}" class="btn btn-primary me-2">Mettre à jour l'Article</a>
            <a href="{% url 'posts:post_delete' post.pk %}" class="btn btn-danger">Supprimer l'Article</a>
          </div>
        {% endif %}
        <div class="card-cont d-flex justify-content-center">
          <div class="img-container card mb-3 d-flex">
            <a href="#"><img src="{{ post.post_image.url }}" class="card-img-top" alt="img del post" /></a>
            <div class="user-data-space d-flex">
              <div class="user-data-space__mini">
                <a href="{{ post.get_absolute_url }}"><img class="rounded-circle" src="{{ post.user.profile_photo.url }}" /></a>
              </div>
              <div class="user-data-space__name">
                <a class="user-data-space__name--bold" href="{{ post.get_absolute_url }}"><p class="author-name">{{ post.user.get_full_name }}</p></a>
                <a class="text-black" href="{{ post.get_absolute_url }}"><p class="reation-date">Posté le {{ post.created_at }}</p></a>
              </div>
            </div>
            <div class="user-data-space__tags card-body">
              <h2 class="card-title">{{ post.title }}</h2>
              <div class="user-data-space__tags--lighter">
                <ul>
                  {% for tag in post.tags.all %}
                    <li>
                      <a href="#"><p>#{{ tag.name }}</p></a>
                    </li>
                  {% endfor %}
                </ul>
              </div>
              <div>{{ post.content }}</div>

              <div class="reactions">
                <p>Total Réactions: {{ post.total_reactions }}</p>
                <div>
                  {% for reaction in post.reaction_summary %}
                    <span>{{ reaction.reaction_type|title }}: {{ reaction.count }}</span>
                  {% endfor %}
                </div>

                <div class="d-flex mt-3">
                  <form method="post" action="{% url 'posts:add_reaction' post.pk 'like' %}">
                    {% csrf_token %}
                    <button type="submit">❤️ Like</button>
                  </form>
                  <form method="post" action="{% url 'posts:add_reaction' post.pk 'laugh' %}">
                    {% csrf_token %}
                    <button type="submit">😄 Amusant</button>
                  </form>
                  <form method="post" action="{% url 'posts:add_reaction' post.pk 'celebrate' %}">
                    {% csrf_token %}
                    <button type="submit">🎉 Célébration</button>
                  </form>
                  <form method="post" action="{% url 'posts:add_reaction' post.pk 'insightful' %}">
                    {% csrf_token %}
                    <button type="submit">💡 Perspicace</button>
                  </form>
                  <form method="post" action="{% url 'posts:add_reaction' post.pk 'curious' %}">
                    {% csrf_token %}
                    <button type="submit">🤔 Curieux</button>
                  </form>
                </div>
              </div>

              <h2 class="mt-5 card-title">Top Commentaires</h2>
              <div>
                <a href="{% url 'posts:create_comment' post.pk %}">Laisser un commentaire</a>
              </div>
              {% for comment in post.comment_set.all %}
                <div class="comment-section">
                  <div class="comment-section__picture">
                    <a href="#"><img src="{{ comment.post.user.profile_photo.url }}" class="rounded-circle" /></a>
                  </div>
                  <div class="comment-section__rectangle">
                    <div class="comment-section__rectangle--username">
                      <a href="#">
                        <h6>{{ comment.post.user.get_full_name }}</h6>
                        <p>{{ comment.created_at }}</p>
                      </a>
                    </div>
                    <div class="comment-section__rectangle--comment">
                      <a href="#"><p>{{ comment.content }}</p></a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </section>
      <asside class="asside-left col-lg-4 d-none d-lg-block">
        <div class="cardUserFollow">
          <div class="cardUserDate">
            <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--DQmJ_XZV--/c_fill,f_auto,fl_progressive,h_90,q_auto,w_90/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/826332/224dd80d-2524-4499-b730-515327a6af1a.jpg" class="cardUserDate__image" alt="..." />
            <a class="cardUserDate__name">Ernane Ferreira</a>
          </div>
          <div class="cardUserFollow__body">
            <button class="cardUserFollow__body--btn btn-primary">Follow</button>
            <p class="cardUserFollow__body--description">A big dreamer, technology lover and software development enthusiast.</p>
            <div class="cardUserFollow__body--informationUser">
              <span class="cardUserFollow__body--datesTitle">LOCATION</span>
              <p class="cardUserFollow__body--datesText">Rio Grande do Norte, Brazil</p>
              <span class="cardUserFollow__body--datesTitle">EDUCATION</span>
              <p class="cardUserFollow__body--datesText">University student of the interdisciplinary bachelor's degree in Science and Technology</p>
              <span class="cardUserFollow__body--datesTitle">PRONOUNS</span>
              <p class="cardUserFollow__body--datesText">Ele/dele</p>
              <span class="cardUserFollow__body--datesTitle">WORK</span>
              <p class="cardUserFollow__body--datesText">Developer at Real Seguro Viagem</p>
              <span class="cardUserFollow__body--datesTitle">JOINED</span>
              <p class="cardUserFollow__body--datesText">Mar 6, 2022</p>
            </div>
          </div>
        </div>
        <div class="cardMoreUser">
          <ul class="cardMoreUser__list list-group list-group-flush">
            <li class="cardMoreUser__list--title list-group-item">
              More from <a href="">Ernane Ferreira</a>
            </li>
            <li class="cardMoreUser__list--text list-group-item">
              <a href="">[pt-br] Guia rápido e prático dos principais comandos git</a><br />
              <span>#</span>git
              <span>#</span>gitlab
              <span>#</span>github
              <span>#</span>codequality
            </li>
          </ul>
        </div>
        <div class="cardCategory">
          <div class="cardCategory__body">
            <div class="cardCategory__body--link">
              <p>DEV Community</p>
              <a href="" name="btn-community" type="button" value=""><img src="/assets/img/icons8-elipsis-28.webp" alt="" /></a>
            </div>
            <p class="cardCategory__body--title card-title">👋 Do you have an org account on DEV?</p>
            <p class="cardCategory__body--description card-title">Maximize the impact of your presence on DEV with our new Pro Tools suite.</p><br />
            <p class="cardCategory__body--subTitle card-title">Get access to:</p><br />
            <ul class="cardCategory__body--list card-title">
              <li>Advanced analytics and insights</li>
              <li>
                The opportunity to use <b>this space</b> next to your own posts to help your readers engage more deeply with your message.
              </li>
            </ul><br />
            <a href="#" class="cardCategory__body--btn btn btn-primary">Try Pro Tools for Free</a>
          </div>
        </div>
      </asside>
    </div>
  </main>

  {% include 'footer.html' %}
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <main class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="container p-0 mt-5">
          <div class="row mt-5">
            <div class="card col-md-6 offset-md-3 p-5 mt-5">
              <h2>Créer un nouvel Article</h2>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Créer</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <main class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="container p-0 mt-5">
          <div class="row mt-5">
            <div class="card col-md-6 offset-md-3 p-5 mt-5">
              <h2>Mise à jour d'un Article</h2>
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Mettre à jour</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}